"""faz2 core domain

Revision ID: 5678faa6d0c4
Revises: 70a5135b18da
Create Date: 2026-09-14 14:10:09.589690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5678faa6d0c4'
down_revision = '70a5135b18da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_expected_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='internship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internships_user_id'), ['user_id'], unique=False)

    op.create_table('daily_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('internship_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('ai_refined_content', sa.Text(), nullable=True),
    sa.Column('ai_status', sa.Enum('PENDING', 'REFINED', 'ACCEPTED', 'REJECTED', 'ERROR', name='ai_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_id', 'date', name='uq_daily_logs_internship_date')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_internship_id'), ['internship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_internship_id'))

    op.drop_table('daily_logs')
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internships_user_id'))

    op.drop_table('internships')
    # ### end Alembic commands ###
